import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, '..');
const outputPath = join(packageRoot, 'src', 'models.ts');

interface FetchModel {
	id: string;
	name: string;
	contextWindow?: number;
}

// ChatGPT subscription models are not exposed through models.dev, but are
// available through the OpenAI Codex OAuth provider.
const CODEX_MODELS: readonly FetchModel[] = [
	{ id: 'gpt-4.1', name: 'GPT-4.1', contextWindow: 1_047_576 },
	{ id: 'gpt-4.1-mini', name: 'GPT-4.1 mini', contextWindow: 1_047_576 },
	{ id: 'gpt-4.1-nano', name: 'GPT-4.1 nano', contextWindow: 1_047_576 },
	{ id: 'gpt-5-codex', name: 'GPT-5-Codex', contextWindow: 400_000 },
	{ id: 'gpt-5.1-codex', name: 'GPT-5.1 Codex', contextWindow: 400_000 },
	{ id: 'gpt-5.1-codex-max', name: 'GPT-5.1 Codex Max', contextWindow: 400_000 },
	{ id: 'gpt-5.1-codex-mini', name: 'GPT-5.1 Codex mini', contextWindow: 400_000 },
	{ id: 'gpt-5.2-codex', name: 'GPT-5.2 Codex', contextWindow: 400_000 },
	{ id: 'gpt-5.3-codex', name: 'GPT-5.3 Codex', contextWindow: 400_000 },
	{ id: 'gpt-5.3-codex-spark', name: 'GPT-5.3 Codex Spark', contextWindow: 128_000 },
	{ id: 'o4-mini', name: 'o4-mini', contextWindow: 200_000 },
];

async function fetchOpenRouterModels(): Promise<FetchModel[]> {
	try {
		const res = await fetch('https://openrouter.ai/api/v1/models', { signal: AbortSignal.timeout(10000) });
		const data = await res.json();
		const list = data.data || [];
		return list
			.filter((m: Record<string, unknown>) => (m.supported_parameters as string[])?.includes('tools'))
			.map((m: Record<string, unknown>) => ({
				id: m.id as string,
				name: (m.name as string) || (m.id as string),
				contextWindow: (m.context_length as number) || undefined,
			}));
	} catch (e) {
		console.warn('Failed to fetch OpenRouter:', e);
		return [];
	}
}

async function main() {
	const orModels = await fetchOpenRouterModels();
	console.log(`OpenRouter: ${orModels.length} models`);

	let devData: Record<
		string,
		{ models: Record<string, { name?: string; tool_call?: boolean; limit?: { context?: number } }> }
	> = {};
	try {
		const res = await fetch('https://models.dev/api.json', { signal: AbortSignal.timeout(10000) });
		devData = await res.json();
		console.log(`models.dev: ${Object.keys(devData).length} providers`);
	} catch (e) {
		console.warn('Failed to fetch models.dev:', e);
	}

	const byProvider: Record<string, Map<string, { name: string; contextWindow?: number }>> = {};

	function addModel(provider: string, id: string, name: string, contextWindow?: number) {
		if (!byProvider[provider]) byProvider[provider] = new Map();
		if (!byProvider[provider].has(id)) {
			byProvider[provider].set(id, { name, contextWindow });
		}
	}

	// Process models.dev
	for (const [providerName, providerData] of Object.entries(devData)) {
		if (!providerData.models) continue;
		for (const [modelId, model] of Object.entries(providerData.models)) {
			if (model.tool_call !== true) continue;
			addModel(providerName, modelId, model.name || modelId, model.limit?.context);
		}
	}

	// Process OpenRouter models — all belong under "openrouter"
	for (const m of orModels) {
		addModel('openrouter', m.id, m.name);
	}

	for (const model of CODEX_MODELS) {
		addModel('openai-codex', model.id, model.name, model.contextWindow);
	}

	// Sort and convert to plain objects
	const sorted: Record<string, { id: string; name: string; contextWindow?: number }[]> = {};
	for (const provider of Object.keys(byProvider).sort()) {
		const models = Array.from(byProvider[provider].entries())
			.map(([id, entry]) => {
				const obj: { id: string; name: string; contextWindow?: number } = { id, name: entry.name };
				if (entry.contextWindow) obj.contextWindow = entry.contextWindow;
				return obj;
			})
			.sort((a, b) => a.name.localeCompare(b.name));
		sorted[provider] = models;
	}

	const output = `// Auto-generated by scripts/generate-models.ts
// Do not edit manually

export interface ModelEntry {
  id: string;
  name: string;
  contextWindow?: number;
}

const MODELS: Record<string, ModelEntry[]> = ${JSON.stringify(sorted, null, 2)};

export function getProviderModels(providerId: string): ModelEntry[] {
  return MODELS[providerId] || [];
}
`;

	writeFileSync(outputPath, output, 'utf-8');
	const totalModels = Object.values(sorted).reduce((sum, m) => sum + m.length, 0);
	console.log(`Generated ${outputPath}`);
	console.log(`${Object.keys(sorted).length} providers, ${totalModels} total models`);
	console.log(
		'Top providers:',
		Object.entries(sorted)
			.sort((a, b) => b[1].length - a[1].length)
			.slice(0, 10)
			.map(([k, v]) => `${k}: ${v.length}`)
			.join(', '),
	);
}

main().catch(console.error);
